# Generated by Django 5.2.4 on 2025-10-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('foundation', 'Yayasan'), ('csr', 'CSR'), ('investor', 'Investor')], max_length=50)),
                ('contact_info', models.TextField()),
            ],
        ),
    ]
