# Generated by Django 5.2.4 on 2025-07-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_alter_investor_total_invesment_alter_investor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='total_invesment',
            new_name='total_investment',
        ),
    ]
