# Generated by Django 5.2.4 on 2025-07-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('lahan', 'Lahan'), ('alat', 'Alat'), ('bangunan', 'Bangunan'), ('ternak', 'Ternak')], max_length=100)),
                ('locations', models.CharField(max_length=100)),
                ('size', models.FloatField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('acquistion_date', models.DateField()),
                ('ownership_status', models.CharField(max_length=50)),
                ('document_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriAset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pemilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kontak', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
