# Generated by Django 5.2.4 on 2025-10-27 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kontak', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nomor_rekening', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Aset')),
                ('type', models.CharField(choices=[('lahan', 'Lahan'), ('alat', 'Alat'), ('bangunan', 'Bangunan'), ('ternak', 'Ternak')], max_length=100, verbose_name='Tipe Aset')),
                ('location', models.CharField(max_length=100, verbose_name='Lokasi')),
                ('size', models.FloatField(verbose_name='Ukuran (m²)')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Nilai Aset')),
                ('acquisition_date', models.DateField(verbose_name='Tanggal Akuisisi')),
                ('ownership_status', models.CharField(choices=[('full_ownership', 'Full Ownership'), ('partial_ownership', 'Partial Ownership'), ('investor_owned', 'Investor Owned'), ('leashold', 'Leased'), ('under_construction', 'Under Construction'), ('personal_ownership', 'Personal Ownership')], max_length=50, verbose_name='Status Kepemilikan')),
                ('document_url', models.TextField(blank=True, null=True, verbose_name='Dokumen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landowner_share_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Bagi Hasil Pemilik')),
                ('landowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='asset.owner', verbose_name='Pemilik Lahan')),
            ],
            options={
                'verbose_name': 'Aset',
                'verbose_name_plural': 'Aset',
            },
        ),
    ]
