# Generated by Django 5.2.4 on 2025-07-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='locations',
            new_name='location',
        ),
    ]
