# Generated by Django 5.2.4 on 2025-07-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_rename_locations_asset_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KategoriAset',
        ),
        migrations.AlterField(
            model_name='asset',
            name='ownership_status',
            field=models.CharField(blank=True, choices=[('full_ownership', 'Full Ownership'), ('partial_ownership', 'Partial Ownership'), ('investor_owned', 'Investor Owned'), ('leashold', 'Leased'), ('under_construction', 'Under Construction'), ('personal_ownership', 'Personal Ownership')], max_length=50),
        ),
    ]
