# Generated by Django 5.2.4 on 2025-10-23 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_rename_pemilik_owner_asset_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Aset', 'verbose_name_plural': 'Aset'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
        migrations.AddField(
            model_name='asset',
            name='landowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='asset.owner', verbose_name='Pemilik Lahan'),
        ),
        migrations.AddField(
            model_name='asset',
            name='landowner_share_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Bagi Hasil Pemilik'),
        ),
        migrations.AddField(
            model_name='owner',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='nomor_rekening',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquistion_date',
            field=models.DateField(verbose_name='Tanggal Akuisisi'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='document_url',
            field=models.TextField(blank=True, null=True, verbose_name='Dokumen'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Lokasi'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama Aset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ownership_status',
            field=models.CharField(choices=[('full_ownership', 'Full Ownership'), ('partial_ownership', 'Partial Ownership'), ('investor_owned', 'Investor Owned'), ('leashold', 'Leased'), ('under_construction', 'Under Construction'), ('personal_ownership', 'Personal Ownership')], max_length=50, verbose_name='Status Kepemilikan'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='size',
            field=models.FloatField(verbose_name='Ukuran (m²)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('lahan', 'Lahan'), ('alat', 'Alat'), ('bangunan', 'Bangunan'), ('ternak', 'Ternak')], max_length=100, verbose_name='Tipe Aset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Nilai Aset'),
        ),
    ]
