# Generated by Django 5.2.4 on 2025-11-10 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('stok', 'Stok'), ('terjual', 'Terjual')], db_index=True, default='stok', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='asset.asset')),
            ],
        ),
    ]
