# Generated by Django 5.2.4 on 2026-01-19 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Produk (Misal: Telur)')),
                ('unit', models.CharField(max_length=20, verbose_name='Satuan (Kg/Liter)')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Stok Saat Ini')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Hasil')),
                ('quality', models.CharField(choices=[('A', 'Grade A (Sangat Baik)'), ('B', 'Grade B (Baik)'), ('C', 'Grade C (Cukup)'), ('rejected', 'Rejected/Rusak')], default='A', max_length=20, verbose_name='Kualitas')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Panen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='asset.asset', verbose_name='Asal Aset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='production.product', verbose_name='Pilih Produk')),
            ],
        ),
    ]
