# Generated by Django 5.2.4 on 2025-11-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('stok', 'Stok'), ('terjual', 'Terjual')], db_index=True, default='stok', max_length=20),
        ),
    ]
