# Generated by Django 5.2.4 on 2026-01-11 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('landowner_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investor_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('distribution_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Distributed', 'Distributed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='production.production')),
            ],
        ),
    ]
