# Generated by Django 5.2.4 on 2025-10-31 03:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('landowner_share', models.DecimalField(decimal_places=2, max_digits=20)),
                ('investor_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('distribution_date', models.DateField(default=django.utils.timezone.now)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='production.production')),
            ],
        ),
    ]
