# Generated by Django 5.2.4 on 2025-07-23 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('profit_distribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitdistribution',
            name='Investor_share',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='distribution_date',
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='landowner_share',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='investor_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
