# Generated by Django 5.2.4 on 2025-12-16 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitdistribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Distributed', 'Distributed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='distribution_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='investor_share',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='landowner_share',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
