# Generated by Django 5.2.4 on 2026-01-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_distribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitdistribution',
            name='details',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='investor_share',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='landowner_share',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='period',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='status',
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='distribution_details',
            field=models.TextField(blank=True, verbose_name='Rincian Hasil (Otomatis)'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='dividend_per_share',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Dividen Per Lembar'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='investor_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Total Jatah Investor'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='landowner_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Total Jatah Landowner'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='retained_earnings',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Sisa Dana (Retained)'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='total_distributed',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Dana Dibagikan (Rp)'),
        ),
    ]
