# Generated by Django 5.2.4 on 2026-01-20 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
        ('profit_distribution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitdistribution',
            name='distribution_details',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='dividend_per_share',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='investor_total_amount',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='landowner_total_amount',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='retained_earnings',
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='total_distributed',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Dana Dibagikan'),
        ),
        migrations.CreateModel(
            name='ProfitDistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah Diterima')),
                ('role', models.CharField(default='Investor', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='profit_distribution.profitdistribution')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funding.funding')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
