# Generated by Django 5.2.4 on 2025-07-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_distribution', '0002_remove_profitdistribution_investor_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitdistribution',
            name='investor_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
