# Generated by Django 5.2.4 on 2025-07-28 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('profit_distribution', '0003_alter_profitdistribution_investor_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitdistribution',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='production.production'),
        ),
    ]
