# Generated by Django 5.2.4 on 2025-07-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='funding_url',
            new_name='funding_id',
        ),
    ]
