# Generated by Django 5.2.4 on 2025-07-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_funding_url_expense_funding_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('material', 'Material'), ('tenaga kerja', 'Tenaga Kerja'), ('transport', 'Transport'), ('feed', 'Pakan'), ('perawatan', 'Perawatan'), ('tools', 'Alat dan Perlengkapan'), ('other', 'Lain-Lain')], max_length=20),
        ),
    ]
