# Generated by Django 5.2.4 on 2025-11-10 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funding_source', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_received', models.DateField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Tersedia'), ('allocated', 'Teralokasi'), ('used', 'Terpakai')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='project.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='funding_source.fundingsource')),
            ],
        ),
    ]
