# Generated by Django 5.2.4 on 2025-10-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='status',
            field=models.CharField(choices=[('available', 'Tersedia'), ('allocated', 'Teralokasi'), ('used', 'Terpakai')], max_length=50),
        ),
    ]
