# Generated by Django 5.2.4 on 2025-12-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundings', to='project.project'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='status',
            field=models.CharField(choices=[('available', 'Tersedia'), ('allocated', 'Dialokasikan'), ('used', 'Digunakan')], default='available', max_length=20),
        ),
    ]
