# Generated by Django 5.2.4 on 2025-10-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Superadmin', 'Superadmin'), ('Admin', 'Admin'), ('Oprator', 'Oprator'), ('Investor', 'Investor'), ('Viewer', 'Viewer')], default='Viewer', max_length=100),
        ),
    ]
