# Generated by Django 5.2.4 on 2025-07-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('funding', '0001_initial'),
        ('investor', '0003_rename_total_invesment_investor_total_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('investment_date', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='asset.asset')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='funding.funding')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='investor.investor')),
            ],
        ),
    ]
