# Generated by Django 5.2.4 on 2025-11-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('funding', '0001_initial'),
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('ownership_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('investment_date', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='asset.asset')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='funding.funding')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='investor.investor')),
            ],
            options={
                'ordering': ['-ownership_percentage'],
            },
        ),
    ]
