# Generated by Django 5.2.4 on 2025-07-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='ownership_precentage',
            field=models.FloatField(default=0.0),
        ),
    ]
