# Generated by Django 5.2.4 on 2025-10-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownership',
            options={'ordering': ['-ownership_percentage']},
        ),
    ]
