# Generated by Django 5.2.4 on 2025-12-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('ownership', '0002_alter_ownership_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='asset.asset'),
        ),
    ]
