# Generated by Django 5.2.4 on 2025-07-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0002_ownership_ownership_precentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='ownership_precentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
