# Generated by Django 5.2.4 on 2026-01-14 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nama Produk Terjual')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah (Qty)')),
                ('unit', models.CharField(max_length=50, verbose_name='Satuan')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Satuan (Rp)')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Total Penjualan')),
                ('buyer_name', models.CharField(blank=True, default='Umum', max_length=255, null=True, verbose_name='Nama Pembeli')),
                ('buyer_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kontak Pembeli')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Transaksi')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='sales/', verbose_name='Bukti Pembayaran')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Penjualan',
                'verbose_name_plural': 'Riwayat Penjualan',
                'ordering': ['-date'],
            },
        ),
    ]
